MarsWearShop/Areas/Admin/Controllers/BaseAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarsWearShop.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "Admin")]
    public abstract class BaseAdminController : Controller
    {
    }
}

MarsWearShop/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarsWearShop.Areas.Admin.Controllers
{
    public class OrderController : BaseAdminController
    {
        public IActionResult List()
        {
            return View();
        }
    }
}

MarsWearShop/Components/CartItemsCountViewComponent.cs
using MarsWearShop.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarsWearShop.Components
{
    public class CartItemsCountViewComponent : ViewComponent
    {
        readonly ICartService Cart;
        public CartItemsCountViewComponent(ICartService cart)
        {
            Cart = cart;
        }

        public async Task<ContentViewComponentResult> InvokeAsync()
        {
            int count = await Cart.GetItemsCount();

            return Content(count > 0 ? count.ToString() : "");
        }
    }
}

MarsWearShop/Components/CartViewComponent.cs
using MarsWearShop.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarsWearShop.Components
{
    public class CartViewComponent : ViewComponent
    {
        readonly ICartService Cart;

        public CartViewComponent(ICartService cart)
        {
            Cart = cart;
        }

        public async Task<ViewViewComponentResult> InvokeAsync()
        {
            return View(await Cart.GetCart());
        }
    }
}

MarsWearShop/Components/MainCategoriesViewComponent.cs
using MarsWearShop.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarsWearShop.Components
{
    public class MainCategoriesViewComponent : ViewComponent
    {
        readonly ICatalogService Catalog;
        public MainCategoriesViewComponent(ICatalogService catalog)
        {
            Catalog = catalog;
        }

        public async Task<ViewViewComponentResult> InvokeAsync()
        {
            return View(await Catalog.GetMainCategories());
        }
    }
}

MarsWearShop/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarsWearShop.Controllers
{
    public class AccountController : Controller
    {
        [HttpPost]
        public JsonResult Login(string login, string password)
        {
            return Json(new { success = false, msg = "Неверный логин или пароль" });
        }
    }
}

MarsWearShop/Controllers/CartController.cs
using MarsWearShop.Data.ViewModels;
using MarsWearShop.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarsWearShop.Controllers
{
    public class CartController : Controller
    {
        readonly ICartService Cart;

        public CartController(ICartService cart)
        {
            Cart = cart;
        }

        [HttpPost]
        public async Task<int> AddToCartItem(int productId, string size)
        {
            return await Cart.AddItem(productId, size);
        }

        [HttpPost]
        public async Task DeleteItem(int id)
        {
            await Cart.DeleteItem(id);
        }

        [HttpPost]
        public async Task ClearCart()
        {
            await Cart.ClearCart();
        }

        [HttpPost]
        public async Task<int> PlusItem(int id)
        {
            return await Cart.PlusItem(id);
        }

        [HttpPost]
        public async Task<int> MinusItem(int id)
        {
            return await Cart.MinusItem(id);
        }

        [HttpPost]
        public async Task<PartialViewResult> LoadNewItem()
        {
            return PartialView("_CartItem", await Cart.GetLastItem());
        }
    }
}

MarsWearShop/Controllers/CatalogController.cs
using MarsWearShop.Data.ViewModels;
using MarsWearShop.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarsWearShop.Controllers
{
    public class CatalogController : Controller
    {
        readonly ICatalogService Catalog;

        public CatalogController(ICatalogService catalog)
        {
            Catalog = catalog;
        }

        [HttpGet, Route("catalog/{**categories}")]
        public async Task<IActionResult> Index(string categories)
        {
            return View(new CatalogVM { Products = await Catalog.GetProducts(categories), Categories = await Catalog.GetCategories(categories) });
        }

        [HttpPost, Route("catalog/{**categories}")]
        public async Task<IActionResult> Index(string categories, int index)
        {
            return PartialView("_ProductsList", await Catalog.GetProducts(categories, index));
        }

        [HttpGet, Route("discount")]
        public async Task<IActionResult> Discount()
        {
            return View(await Catalog.GetProductsOnDiscountPage());
        }

        [HttpPost, Route("discount")]
        public async Task<IActionResult> Discount(int index)
        {
            return PartialView("_ProductsList",await Catalog.GetProductsOnDiscountPage(index));
        }


        [Route("catalog/product/{id}")]
        public async Task<IActionResult> Product(int id)
        {
            return View(await Catalog.GetProduct(id));
        }
    }
}

MarsWearShop/Controllers/HomeController.cs
using MarsWearShop.Classes;
using MarsWearShop.Data;
using MarsWearShop.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MarsWearShop.Controllers
{
    public class HomeController : Controller
    {
        readonly ICatalogService Catalog;
        public HomeController(ICatalogService catalog)
        {
            Catalog = catalog;
        }

        public async Task<IActionResult> Index()
        {
            return View(await Catalog.GetProductsOnMainPage());
        }

        [Route("error")]
        public IActionResult Error()
        {
            return View();
        }

        [Route("about")]
        public IActionResult About()
        {
            return View();
        }
    }
}

MarsWearShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarsWearShop.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MarsWearShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

MarsWearShop/Views/Catalog/Discount.cshtml
@model IEnumerable<ProductCardVM>

@{ 
    ViewBag.Title = "Акции Mars Wear Shop";
}

<div id="discount-page" class="container">
    @if (Model.Any())
    {
        @await Html.PartialAsync("_ProductsList", Model)
        @await Html.PartialAsync("_ShowMore")
    }
    else
    {
        @await Html.PartialAsync("_PageMsg", "Не найдено действительных акций.")
    }
</div>

MarsWearShop/Views/Catalog/Index.cshtml
@model CatalogVM

@{
    ViewBag.Title = "Каталог Mars Wear Shop";
}

<div id="catalog" class="container">
    @if (Model.Products.Any())
    {
        @await Html.PartialAsync("_CategoriesList", Model.Categories);
        @await Html.PartialAsync("_ProductsList", Model.Products);
        @await Html.PartialAsync("_ShowMore");
    }
    else
    {
        @await Html.PartialAsync("_PageMsg", "Продукты не найдены.");
    }
</div>

MarsWearShop/Views/Catalog/Product.cshtml
@model Product

@if (Model == null)
{
    @await Html.PartialAsync("_PageMsg", "Товар не найден.")   
}
else
{

}

MarsWearShop/Views/Catalog/_CategoriesList.cshtml
@model IEnumerable<CategoryVM>

@if (Model.Any())
{
    <div class="categories-box">
        <span class="header-font">категории</span><br />
        <div class="categories-container">
                @foreach (var item in Model)
                {
                    <a class="category header-font" href="@Context.Request.Path/@item.Link">@item.Name</a>
                }
        </div>
    </div>
}

MarsWearShop/Views/Home/About.cshtml
@{ 
    ViewBag.Title = "О нас Mars Wear Shop";
}

<div id="about-page" class="container">
    <div class="frame-box">
        <iframe src="https://www.youtube-nocookie.com/embed/hxJvqglWWtU?start=19" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
</div>

MarsWearShop/Views/Home/Index.cshtml
@{ 
    ViewBag.Title = "Главная Mars Wear Shop";
}

@model IEnumerable<ProductCardVM>

<div id="main-page" class="container">
    @await Html.PartialAsync("_ProductsList", Model)
</div>

MarsWearShop/Views/Shared/Components/Cart/Default.cshtml
@model IEnumerable<CartItemVM>

<div id="cart-background" onclick="CloseCart()"></div>
<div id="cart">
    <div class="top">
        <button onclick="CloseCart()">
            <img src="~/icon/close.png" />
        </button>
    </div>
    <div class="cart-items-box">
        <p align="center" class="cart-msg header-font">ваша корзина пуста</p>
        @foreach (CartItemVM item in Model)
        {
            @await Html.PartialAsync("_CartItem", item)
        }
    </div>
    <div class="bottom">
        <div class="total-price-box header-font">итого:&emsp;₴ <span class="total-price"></span></div>
        <div class="buttons-box">
            <a class="btn header-font">заказать</a>
            <button class="btn header-font clear-cart" onclick="ClearCart()">очистить</button>
        </div>
    </div>
</div>

MarsWearShop/Views/Shared/Components/MainCategories/Default.cshtml
@model IEnumerable<CategoryVM>

<div class="categories-box">
    @foreach (CategoryVM item in Model)
    {
        <a class="category header-font" href="/catalog/@item.Link">@item.Name</a>
    }
</div>

MarsWearShop/Views/Shared/_CartItem.cshtml
@model CartItemVM

<div class="cart-item" data-prodId="@Model.ProductId">
    <img src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Img))" />
    <div class="data">
        <div class="name"><a class="header-font" href="/catalog/product/@Model.ProductId">@Model.Name</a></div>
        <div class="options">
            <div class="size header-font">
                <span @if (Model.Size == "NoSize")@("style=display:none") >@Model.Size</span>
            </div>
            <div class="count">
                <div class="num-container">
                    <button onclick="CartItemMinus(event)" value="@Model.Id">&#8722;</button>
                    <span data-max-count="@Model.MaxCount" class="count header-font">@Model.Count</span>
                    <button onclick="CartItemPlus(event)" value="@Model.Id">&#43;</button>
                </div>
            </div>
            <div class="delete-btn-box">
                <button onclick="CartItemDelete(event)" value="@Model.Id">
                    <img src="~/icon/close.png" />
                </button>
            </div>
        </div>
        <div class="price header-font">
            ₴<span data-price="@Model.Price" class="item-sum"></span>
        </div>
        <div>
            <small class="num-in-stock" @if (Model.MaxCount < Model.Count)@("style=color:red") >В наличии: @Model.MaxCount</small>
        </div>
    </div>
</div>

MarsWearShop/Views/Shared/_Footer.cshtml
<footer>
    
</footer>

MarsWearShop/Views/Shared/_Header.cshtml
<header>
    <div class="content">
        <div class="header menu-toggler-box">
            <button onclick="toggleMenu()">
                <div class="line first"></div>
                <div class="line middle"></div>
                <div class="line last"></div>
            </button>
        </div>
        <div class="header logo-box">
            <a href="/">
                <img id="logo" src="~/img/logo.png" alt="logo" />
            </a>
        </div>
        <div class="header account-box">
            <button onclick="openForm()">
                <img class="icon" src="~/icon/user.png" alt="account" />
            </button>
        </div>
        <div class="header cart-box">
            <button onclick="OpenCart()">
                <img class="icon" src="~/icon/cart.png" alt="cart" />
                <div class="content">
                    <span class="header-font cart-items-count">@await Component.InvokeAsync("CartItemsCount")</span>
                </div>
            </button>
        </div>
        <div class="header contact-box">
            <span class="header-font">тел: (380)-95-32-43-078</span>
        </div>
    </div>
</header>

MarsWearShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/icon/icon.png" type="image/x-icon" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
</head>
<body onload="startPage()" onresize="resizePage()" onscroll="scrollPage()">
    @await Component.InvokeAsync("Cart")
    @await Html.PartialAsync("_SignIn")
    @await Html.PartialAsync("_Header")
    @await Html.PartialAsync("_Navigation")

    <main>
        @RenderBody()
    </main>

    @await Html.PartialAsync("_Footer")

    <div id="scroll-to-top" onclick="scrollToTop()">
        <img src="~/icon/top.png" />
    </div>

    <script src="~/js/site.js"></script>
</body>
</html>

MarsWearShop/Views/Shared/_Navigation.cshtml
<nav>
    <div class="content">
        <div class="nav first">
            <div class="account-box">
                <button class="account-btn" onclick="openForm()">
                    <img class="icon" src="~/icon/user.png" alt="account" />
                </button>
            </div>
        </div>
        <div class="nav catalog-box">
            <a href="/catalog"></a>
            <div class="content">
                <span class="header-font">каталог</span><button class="catalog-toggler" onclick="toggleCategories()"><img src="~/icon/openlist.png" /></button>
            </div>
            @await Component.InvokeAsync("MainCategories")
        </div>
        <div class="nav">
            <a class="header-font" href="/discount">акции</a>
        </div>
        <div class="nav">
            <a class="header-font" href="">оплата и доставка</a>
        </div>
        <div class="nav">
            <a class="header-font" href="/about">о нас</a>
        </div>
    </div>
</nav>
<div id="nav-shadow-box" onclick="toggleMenu()"></div>

MarsWearShop/Views/Shared/_PageMsg.cshtml
@model string

<h2 class="page-msg">
    <span>@Model</span>
</h2>

MarsWearShop/Views/Shared/_ProductsList.cshtml
@model IEnumerable<ProductCardVM>

@if (!Model.Any())
{
    @await Html.PartialAsync("_PageMsg", "Товары не найдены.")
}
else
{
    <div class="products-list">
        @foreach (var item in Model)
        {
            <div class="product-card">
                <div class="top-box">
                    <div class="sizes-box @if (item.Sizes.Any(x => x == "NoSize"))@("hide")">
                        @for (int i = 0; i < item.Sizes.Length; i++)
                        {
                            <label>
                                <input class="size-btn" name="@item.Id" value="@item.Sizes[i]" type="radio" @if (i == 0)@("checked") />
                                <span>@item.Sizes[i]</span>
                            </label>
                        }
                    </div>
                    <a class="img-box" href="/catalog/product/@item.Id">
                        @if (item.IsDiscount)
                        {
                            <div class="discount-attribute header-font">
                                <span>-@item.DiscountProcent%</span>
                            </div>
                        }
                        <img onmouseover="getAdditionalImg(event)" onmouseout="getTitleImg(event)" src="data:image/jpeg;base64,@(Convert.ToBase64String(item.TitleImg))" data-additional="data:image/jpeg;base64,@(Convert.ToBase64String(item.AdditionalImg))" />
                    </a>
                    <div class="to-cart-result header-font" onclick="hideThis(event)">добавлено:&nbsp;<span></span></div>
                </div>
                <div class="info-box">
                    <a href="/catalog/product/@item.Id">
                        <div class="name">@item.Name</div>
                        <div class="price header-font">
                            @if (item.IsDiscount)
                            {
                                <s>₴ @item.FullPrice.ToString("F2")</s>
                            }
                            <span>₴ @item.CurrPrice.ToString("F2")</span>
                        </div>
                    </a>
                </div>
                <button class="in-cart-btn header-font" data-prod-id="@item.Id" onclick="AddToCartItem(event)">в корзину</button>
            </div>
        }
    </div>
}

MarsWearShop/Views/Shared/_ShowMore.cshtml
<div class="show-more-box">
    <button class="show-more-btn header-font" onclick="showMore()">показать больше</button>
</div>

MarsWearShop/Views/Shared/_SignIn.cshtml
<div id="sign-in-box" @if(Context.Request.Query.ContainsKey("ReturnUrl")) @("class=active")>
    <div class="background" onclick="closeForm()"></div>
    <form>
        <div class="top-box">
            <span class="header-font">вход</span>
            <button type="button" class="close" onclick="closeForm()"><img src="~/icon/close.png" /></button>
        </div>
        <div class="msg-box">
            <small></small>
        </div>
        <div class="form-group">
            <label class="header-font">логин</label>
            <input name="login" class="text-input" type="email" required />
        </div>
        <div class="form-group">
            <label class="header-font">пароль</label>
            <input name="password" class="text-input" type="password" required />
        </div>
        <div class="form-checkbox-group">
            <label>
                <input type="checkbox" />
                <span class="checkbox"></span>
                <span class="text header-font">запомнить меня</span>
            </label>
        </div>
        <div class="form-group">
            <button type="button" class="sign-in-btn header-font" onclick="signIn()">войти</button>
        </div>
        <div class="links-box">
            <a href="">зарегистрироваться</a>
            <a href="">забыли пароль?</a>
        </div>
    </form>
</div>